//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var result_ttypes = require('./result_types')


var ttypes = require('./fileUpload_types');
//HELPER FUNCTIONS AND STRUCTURES

FileForCardServ_fileToTY_args = function(args) {
  this.param = null;
  if (args) {
    if (args.param !== undefined) {
      this.param = args.param;
    }
  }
};
FileForCardServ_fileToTY_args.prototype = {};
FileForCardServ_fileToTY_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.param = new ttypes.FileParam();
        this.param.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FileForCardServ_fileToTY_args.prototype.write = function(output) {
  output.writeStructBegin('FileForCardServ_fileToTY_args');
  if (this.param !== null && this.param !== undefined) {
    output.writeFieldBegin('param', Thrift.Type.STRUCT, 1);
    this.param.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

FileForCardServ_fileToTY_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
FileForCardServ_fileToTY_result.prototype = {};
FileForCardServ_fileToTY_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new result_ttypes.StringResult();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FileForCardServ_fileToTY_result.prototype.write = function(output) {
  output.writeStructBegin('FileForCardServ_fileToTY_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

FileForCardServ_auditPass_args = function(args) {
  this.param = null;
  if (args) {
    if (args.param !== undefined) {
      this.param = args.param;
    }
  }
};
FileForCardServ_auditPass_args.prototype = {};
FileForCardServ_auditPass_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.param = new ttypes.AuditParam();
        this.param.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FileForCardServ_auditPass_args.prototype.write = function(output) {
  output.writeStructBegin('FileForCardServ_auditPass_args');
  if (this.param !== null && this.param !== undefined) {
    output.writeFieldBegin('param', Thrift.Type.STRUCT, 1);
    this.param.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

FileForCardServ_auditPass_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
FileForCardServ_auditPass_result.prototype = {};
FileForCardServ_auditPass_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new result_ttypes.Result();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FileForCardServ_auditPass_result.prototype.write = function(output) {
  output.writeStructBegin('FileForCardServ_auditPass_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

FileForCardServ_queryCardsList_args = function(args) {
  this.conditions = null;
  if (args) {
    if (args.conditions !== undefined) {
      this.conditions = args.conditions;
    }
  }
};
FileForCardServ_queryCardsList_args.prototype = {};
FileForCardServ_queryCardsList_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.conditions = new ttypes.QueryConditions();
        this.conditions.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FileForCardServ_queryCardsList_args.prototype.write = function(output) {
  output.writeStructBegin('FileForCardServ_queryCardsList_args');
  if (this.conditions !== null && this.conditions !== undefined) {
    output.writeFieldBegin('conditions', Thrift.Type.STRUCT, 1);
    this.conditions.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

FileForCardServ_queryCardsList_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
FileForCardServ_queryCardsList_result.prototype = {};
FileForCardServ_queryCardsList_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.ThirdPartyCardResultList();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FileForCardServ_queryCardsList_result.prototype.write = function(output) {
  output.writeStructBegin('FileForCardServ_queryCardsList_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

FileForCardServ_addRecharge_args = function(args) {
  this.recharge = null;
  if (args) {
    if (args.recharge !== undefined) {
      this.recharge = args.recharge;
    }
  }
};
FileForCardServ_addRecharge_args.prototype = {};
FileForCardServ_addRecharge_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.recharge = new ttypes.Recharge();
        this.recharge.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FileForCardServ_addRecharge_args.prototype.write = function(output) {
  output.writeStructBegin('FileForCardServ_addRecharge_args');
  if (this.recharge !== null && this.recharge !== undefined) {
    output.writeFieldBegin('recharge', Thrift.Type.STRUCT, 1);
    this.recharge.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

FileForCardServ_addRecharge_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
FileForCardServ_addRecharge_result.prototype = {};
FileForCardServ_addRecharge_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new result_ttypes.Result();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FileForCardServ_addRecharge_result.prototype.write = function(output) {
  output.writeStructBegin('FileForCardServ_addRecharge_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

FileForCardServ_updateRecharge_args = function(args) {
  this.recharge = null;
  if (args) {
    if (args.recharge !== undefined) {
      this.recharge = args.recharge;
    }
  }
};
FileForCardServ_updateRecharge_args.prototype = {};
FileForCardServ_updateRecharge_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.recharge = new ttypes.Recharge();
        this.recharge.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FileForCardServ_updateRecharge_args.prototype.write = function(output) {
  output.writeStructBegin('FileForCardServ_updateRecharge_args');
  if (this.recharge !== null && this.recharge !== undefined) {
    output.writeFieldBegin('recharge', Thrift.Type.STRUCT, 1);
    this.recharge.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

FileForCardServ_updateRecharge_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
FileForCardServ_updateRecharge_result.prototype = {};
FileForCardServ_updateRecharge_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new result_ttypes.Result();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FileForCardServ_updateRecharge_result.prototype.write = function(output) {
  output.writeStructBegin('FileForCardServ_updateRecharge_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

FileForCardServ_rechargeNotify_args = function(args) {
  this.notifyRecharge = null;
  if (args) {
    if (args.notifyRecharge !== undefined) {
      this.notifyRecharge = args.notifyRecharge;
    }
  }
};
FileForCardServ_rechargeNotify_args.prototype = {};
FileForCardServ_rechargeNotify_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.notifyRecharge = new ttypes.NotifyRecharge();
        this.notifyRecharge.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FileForCardServ_rechargeNotify_args.prototype.write = function(output) {
  output.writeStructBegin('FileForCardServ_rechargeNotify_args');
  if (this.notifyRecharge !== null && this.notifyRecharge !== undefined) {
    output.writeFieldBegin('notifyRecharge', Thrift.Type.STRUCT, 1);
    this.notifyRecharge.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

FileForCardServ_rechargeNotify_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
FileForCardServ_rechargeNotify_result.prototype = {};
FileForCardServ_rechargeNotify_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new result_ttypes.Result();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FileForCardServ_rechargeNotify_result.prototype.write = function(output) {
  output.writeStructBegin('FileForCardServ_rechargeNotify_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

FileForCardServ_rechargeList_args = function(args) {
  this.states = null;
  this.reqOutNo = null;
  if (args) {
    if (args.states !== undefined) {
      this.states = args.states;
    }
    if (args.reqOutNo !== undefined) {
      this.reqOutNo = args.reqOutNo;
    }
  }
};
FileForCardServ_rechargeList_args.prototype = {};
FileForCardServ_rechargeList_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.LIST) {
        var _size16 = 0;
        var _rtmp320;
        this.states = [];
        var _etype19 = 0;
        _rtmp320 = input.readListBegin();
        _etype19 = _rtmp320.etype;
        _size16 = _rtmp320.size;
        for (var _i21 = 0; _i21 < _size16; ++_i21)
        {
          var elem22 = null;
          elem22 = input.readI32();
          this.states.push(elem22);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.reqOutNo = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FileForCardServ_rechargeList_args.prototype.write = function(output) {
  output.writeStructBegin('FileForCardServ_rechargeList_args');
  if (this.states !== null && this.states !== undefined) {
    output.writeFieldBegin('states', Thrift.Type.LIST, 1);
    output.writeListBegin(Thrift.Type.I32, this.states.length);
    for (var iter23 in this.states)
    {
      if (this.states.hasOwnProperty(iter23))
      {
        iter23 = this.states[iter23];
        output.writeI32(iter23);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.reqOutNo !== null && this.reqOutNo !== undefined) {
    output.writeFieldBegin('reqOutNo', Thrift.Type.STRING, 2);
    output.writeString(this.reqOutNo);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

FileForCardServ_rechargeList_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
FileForCardServ_rechargeList_result.prototype = {};
FileForCardServ_rechargeList_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.RechargeListResult();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FileForCardServ_rechargeList_result.prototype.write = function(output) {
  output.writeStructBegin('FileForCardServ_rechargeList_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

FileForCardServClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
FileForCardServClient.prototype = {};
FileForCardServClient.prototype.seqid = function() { return this._seqid; }
FileForCardServClient.prototype.new_seqid = function() { return this._seqid += 1; }
FileForCardServClient.prototype.fileToTY = function(param, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_fileToTY(param);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_fileToTY(param);
  }
};

FileForCardServClient.prototype.send_fileToTY = function(param) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('fileToTY', Thrift.MessageType.CALL, this.seqid());
  var args = new FileForCardServ_fileToTY_args();
  args.param = param;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

FileForCardServClient.prototype.recv_fileToTY = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new FileForCardServ_fileToTY_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('fileToTY failed: unknown result');
};
FileForCardServClient.prototype.auditPass = function(param, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_auditPass(param);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_auditPass(param);
  }
};

FileForCardServClient.prototype.send_auditPass = function(param) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('auditPass', Thrift.MessageType.CALL, this.seqid());
  var args = new FileForCardServ_auditPass_args();
  args.param = param;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

FileForCardServClient.prototype.recv_auditPass = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new FileForCardServ_auditPass_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('auditPass failed: unknown result');
};
FileForCardServClient.prototype.queryCardsList = function(conditions, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_queryCardsList(conditions);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_queryCardsList(conditions);
  }
};

FileForCardServClient.prototype.send_queryCardsList = function(conditions) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('queryCardsList', Thrift.MessageType.CALL, this.seqid());
  var args = new FileForCardServ_queryCardsList_args();
  args.conditions = conditions;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

FileForCardServClient.prototype.recv_queryCardsList = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new FileForCardServ_queryCardsList_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('queryCardsList failed: unknown result');
};
FileForCardServClient.prototype.addRecharge = function(recharge, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_addRecharge(recharge);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_addRecharge(recharge);
  }
};

FileForCardServClient.prototype.send_addRecharge = function(recharge) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('addRecharge', Thrift.MessageType.CALL, this.seqid());
  var args = new FileForCardServ_addRecharge_args();
  args.recharge = recharge;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

FileForCardServClient.prototype.recv_addRecharge = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new FileForCardServ_addRecharge_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('addRecharge failed: unknown result');
};
FileForCardServClient.prototype.updateRecharge = function(recharge, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_updateRecharge(recharge);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_updateRecharge(recharge);
  }
};

FileForCardServClient.prototype.send_updateRecharge = function(recharge) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('updateRecharge', Thrift.MessageType.CALL, this.seqid());
  var args = new FileForCardServ_updateRecharge_args();
  args.recharge = recharge;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

FileForCardServClient.prototype.recv_updateRecharge = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new FileForCardServ_updateRecharge_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('updateRecharge failed: unknown result');
};
FileForCardServClient.prototype.rechargeNotify = function(notifyRecharge, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_rechargeNotify(notifyRecharge);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_rechargeNotify(notifyRecharge);
  }
};

FileForCardServClient.prototype.send_rechargeNotify = function(notifyRecharge) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('rechargeNotify', Thrift.MessageType.CALL, this.seqid());
  var args = new FileForCardServ_rechargeNotify_args();
  args.notifyRecharge = notifyRecharge;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

FileForCardServClient.prototype.recv_rechargeNotify = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new FileForCardServ_rechargeNotify_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('rechargeNotify failed: unknown result');
};
FileForCardServClient.prototype.rechargeList = function(states, reqOutNo, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_rechargeList(states, reqOutNo);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_rechargeList(states, reqOutNo);
  }
};

FileForCardServClient.prototype.send_rechargeList = function(states, reqOutNo) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('rechargeList', Thrift.MessageType.CALL, this.seqid());
  var args = new FileForCardServ_rechargeList_args();
  args.states = states;
  args.reqOutNo = reqOutNo;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

FileForCardServClient.prototype.recv_rechargeList = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new FileForCardServ_rechargeList_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('rechargeList failed: unknown result');
};
FileForCardServProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
FileForCardServProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

FileForCardServProcessor.prototype.process_fileToTY = function(seqid, input, output) {
  var args = new FileForCardServ_fileToTY_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.fileToTY.length === 1) {
    Q.fcall(this._handler.fileToTY, args.param)
      .then(function(result) {
        var result = new FileForCardServ_fileToTY_result({success: result});
        output.writeMessageBegin("fileToTY", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new FileForCardServ_fileToTY_result(err);
        output.writeMessageBegin("fileToTY", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.fileToTY(args.param,  function (err, result) {
      var result = new FileForCardServ_fileToTY_result((err != null ? err : {success: result}));
      output.writeMessageBegin("fileToTY", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

FileForCardServProcessor.prototype.process_auditPass = function(seqid, input, output) {
  var args = new FileForCardServ_auditPass_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.auditPass.length === 1) {
    Q.fcall(this._handler.auditPass, args.param)
      .then(function(result) {
        var result = new FileForCardServ_auditPass_result({success: result});
        output.writeMessageBegin("auditPass", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new FileForCardServ_auditPass_result(err);
        output.writeMessageBegin("auditPass", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.auditPass(args.param,  function (err, result) {
      var result = new FileForCardServ_auditPass_result((err != null ? err : {success: result}));
      output.writeMessageBegin("auditPass", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

FileForCardServProcessor.prototype.process_queryCardsList = function(seqid, input, output) {
  var args = new FileForCardServ_queryCardsList_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.queryCardsList.length === 1) {
    Q.fcall(this._handler.queryCardsList, args.conditions)
      .then(function(result) {
        var result = new FileForCardServ_queryCardsList_result({success: result});
        output.writeMessageBegin("queryCardsList", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new FileForCardServ_queryCardsList_result(err);
        output.writeMessageBegin("queryCardsList", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.queryCardsList(args.conditions,  function (err, result) {
      var result = new FileForCardServ_queryCardsList_result((err != null ? err : {success: result}));
      output.writeMessageBegin("queryCardsList", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

FileForCardServProcessor.prototype.process_addRecharge = function(seqid, input, output) {
  var args = new FileForCardServ_addRecharge_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.addRecharge.length === 1) {
    Q.fcall(this._handler.addRecharge, args.recharge)
      .then(function(result) {
        var result = new FileForCardServ_addRecharge_result({success: result});
        output.writeMessageBegin("addRecharge", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new FileForCardServ_addRecharge_result(err);
        output.writeMessageBegin("addRecharge", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.addRecharge(args.recharge,  function (err, result) {
      var result = new FileForCardServ_addRecharge_result((err != null ? err : {success: result}));
      output.writeMessageBegin("addRecharge", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

FileForCardServProcessor.prototype.process_updateRecharge = function(seqid, input, output) {
  var args = new FileForCardServ_updateRecharge_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.updateRecharge.length === 1) {
    Q.fcall(this._handler.updateRecharge, args.recharge)
      .then(function(result) {
        var result = new FileForCardServ_updateRecharge_result({success: result});
        output.writeMessageBegin("updateRecharge", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new FileForCardServ_updateRecharge_result(err);
        output.writeMessageBegin("updateRecharge", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.updateRecharge(args.recharge,  function (err, result) {
      var result = new FileForCardServ_updateRecharge_result((err != null ? err : {success: result}));
      output.writeMessageBegin("updateRecharge", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

FileForCardServProcessor.prototype.process_rechargeNotify = function(seqid, input, output) {
  var args = new FileForCardServ_rechargeNotify_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.rechargeNotify.length === 1) {
    Q.fcall(this._handler.rechargeNotify, args.notifyRecharge)
      .then(function(result) {
        var result = new FileForCardServ_rechargeNotify_result({success: result});
        output.writeMessageBegin("rechargeNotify", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new FileForCardServ_rechargeNotify_result(err);
        output.writeMessageBegin("rechargeNotify", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.rechargeNotify(args.notifyRecharge,  function (err, result) {
      var result = new FileForCardServ_rechargeNotify_result((err != null ? err : {success: result}));
      output.writeMessageBegin("rechargeNotify", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

FileForCardServProcessor.prototype.process_rechargeList = function(seqid, input, output) {
  var args = new FileForCardServ_rechargeList_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.rechargeList.length === 2) {
    Q.fcall(this._handler.rechargeList, args.states, args.reqOutNo)
      .then(function(result) {
        var result = new FileForCardServ_rechargeList_result({success: result});
        output.writeMessageBegin("rechargeList", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new FileForCardServ_rechargeList_result(err);
        output.writeMessageBegin("rechargeList", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.rechargeList(args.states, args.reqOutNo,  function (err, result) {
      var result = new FileForCardServ_rechargeList_result((err != null ? err : {success: result}));
      output.writeMessageBegin("rechargeList", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

